version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_URL: postgres://admin:password@db:5432/mydatabase
    env_file: 
      - .env  # Load the .env file here
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: node-app
  
  db:
    image: postgres:alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
